-- H2-friendly version of V1. Replaces jsonb with clob and drops the
-- Postgres-specific check constraints; behavior is the same for tests.

CREATE TABLE merchants (
    id             UUID PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    api_key_hash   VARCHAR(255) NOT NULL UNIQUE,
    webhook_secret VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE customers (
    id          UUID PRIMARY KEY,
    merchant_id UUID NOT NULL,
    email       VARCHAR(255),
    name        VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_merchant FOREIGN KEY (merchant_id) REFERENCES merchants(id)
);

CREATE TABLE payment_intents (
    id             UUID PRIMARY KEY,
    merchant_id    UUID NOT NULL,
    customer_id    UUID,
    amount_cents   BIGINT NOT NULL,
    currency       CHAR(3) NOT NULL,
    status         VARCHAR(32) NOT NULL,
    provider       VARCHAR(32) NOT NULL DEFAULT 'stripe',
    provider_id    VARCHAR(255) UNIQUE,
    description    VARCHAR(1024),
    metadata_json  CLOB NOT NULL DEFAULT '{}',
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE charges (
    id                  UUID PRIMARY KEY,
    intent_id           UUID NOT NULL,
    attempt_no          INT NOT NULL,
    status              VARCHAR(16) NOT NULL,
    provider_charge_id  VARCHAR(255) UNIQUE,
    failure_code        VARCHAR(64),
    failure_message     VARCHAR(1024),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_charges UNIQUE (intent_id, attempt_no)
);

CREATE TABLE refunds (
    id                  UUID PRIMARY KEY,
    intent_id           UUID NOT NULL,
    amount_cents        BIGINT NOT NULL,
    status              VARCHAR(16) NOT NULL,
    reason              VARCHAR(512),
    provider_refund_id  VARCHAR(255) UNIQUE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE idempotency_keys (
    merchant_id     UUID NOT NULL,
    key             VARCHAR(255) NOT NULL,
    request_hash    VARCHAR(255) NOT NULL,
    response_status INT,
    response_body   CLOB,
    completed_at    TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (merchant_id, key)
);

CREATE TABLE webhook_events (
    id                  UUID PRIMARY KEY,
    provider            VARCHAR(32) NOT NULL,
    provider_event_id   VARCHAR(255) NOT NULL,
    event_type          VARCHAR(128) NOT NULL,
    payload             CLOB NOT NULL,
    status              VARCHAR(16) NOT NULL,
    error               VARCHAR(1024),
    received_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_webhook_events UNIQUE (provider, provider_event_id)
);

CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_type     VARCHAR(32) NOT NULL,
    actor_id       VARCHAR(255),
    action         VARCHAR(255) NOT NULL,
    resource_type  VARCHAR(64) NOT NULL,
    resource_id    VARCHAR(255),
    request_hash   VARCHAR(255),
    result         VARCHAR(16) NOT NULL,
    detail         CLOB,
    at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
